Header: Abrar Jahin
docs/assets/WhatsApp Image 2026-04-15 at 4.58.27 PM.jpeg
About me: I am a business major student at Pacific State University, Los Angeles, CA. Trying to learn as much as possible for better knowledge in life.
Skills: Graphic Designer, Hardworker, Video Gamer, Student, Religious 
Project: No projects so far
Email: p25866@psuca.edu
Theme: jeky11-theme-minimal
